# Generated by Django 5.1.4 on 2025-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDB', '0002_crawlresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlresult',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='media_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='page_speed',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='seo_suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='suggested_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
