# Generated by Django 5.1.4 on 2025-04-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDB', '0003_crawlresult_file_size_crawlresult_media_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyDB.signup'),
        ),
    ]
