# Generated by Django 5.1.4 on 2025-04-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDB', '0004_alter_crawl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDB.signup'),
        ),
    ]
