# Generated by Django 5.1.4 on 2025-04-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDB', '0005_alter_crawl_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawl',
            old_name='user',
            new_name='username',
        ),
    ]
