# Generated by Django 5.1.4 on 2025-04-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDB', '0007_remove_crawl_username_crawl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl',
            name='user',
        ),
        migrations.AddField(
            model_name='crawl',
            name='crawl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyDB.signup'),
            preserve_default=False,
        ),
    ]
